"""create accounts and notes tables

Revision ID: e3e2675e2d04
Revises: 
Create Date: 2026-05-12 01:38:13.539410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e2675e2d04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table("accounts",
                    sa.Column('id',sa.Integer(),nullable=False),
                    sa.Column('email',sa.String(),nullable=False),
                    sa.Column('password',sa.String(),nullable=False),
                    sa.Column('created_at',sa.TIMESTAMP(timezone=True),server_default=sa.text('now()'),nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'))
    

    op.create_table("notes",
                    sa.Column('id',sa.Integer(),nullable=False),
                    sa.Column('title',sa.String(),nullable=False),
                    sa.Column('content',sa.String(),nullable=False),
                    sa.Column('created_at',sa.TIMESTAMP(timezone=True),server_default=sa.text('now()'),nullable=False),
                    sa.Column('account_id',sa.Integer(),nullable=False),
                    sa.Column('bookmark',sa.Boolean(),nullable=True),
                    
                    sa.ForeignKeyConstraint(['account_id'],['accounts.id'],ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'))
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('notes')
    op.drop_table('accounts')
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
